// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: todo.proto

package todov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TodoDomain_CreateTodo_FullMethodName   = "/todo.v1.TodoDomain/CreateTodo"
	TodoDomain_CompleteTodo_FullMethodName = "/todo.v1.TodoDomain/CompleteTodo"
	TodoDomain_ListTodos_FullMethodName    = "/todo.v1.TodoDomain/ListTodos"
	TodoDomain_DeleteTodo_FullMethodName   = "/todo.v1.TodoDomain/DeleteTodo"
	TodoDomain_EditTodo_FullMethodName     = "/todo.v1.TodoDomain/EditTodo"
)

// TodoDomainClient is the client API for TodoDomain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TodoDomain service provides core business logic for managing todos
type TodoDomainClient interface {
	// CreateTodo creates a new todo item
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error)
	// CompleteTodo marks a todo as completed
	CompleteTodo(ctx context.Context, in *CompleteTodoRequest, opts ...grpc.CallOption) (*CompleteTodoResponse, error)
	// ListTodos retrieves all todos for a user
	ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error)
	// DeleteTodo soft-deletes a todo
	DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error)
	// EditTodo updates a todo's title or description
	EditTodo(ctx context.Context, in *EditTodoRequest, opts ...grpc.CallOption) (*EditTodoResponse, error)
}

type todoDomainClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoDomainClient(cc grpc.ClientConnInterface) TodoDomainClient {
	return &todoDomainClient{cc}
}

func (c *todoDomainClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*CreateTodoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTodoResponse)
	err := c.cc.Invoke(ctx, TodoDomain_CreateTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoDomainClient) CompleteTodo(ctx context.Context, in *CompleteTodoRequest, opts ...grpc.CallOption) (*CompleteTodoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTodoResponse)
	err := c.cc.Invoke(ctx, TodoDomain_CompleteTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoDomainClient) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTodosResponse)
	err := c.cc.Invoke(ctx, TodoDomain_ListTodos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoDomainClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*DeleteTodoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTodoResponse)
	err := c.cc.Invoke(ctx, TodoDomain_DeleteTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoDomainClient) EditTodo(ctx context.Context, in *EditTodoRequest, opts ...grpc.CallOption) (*EditTodoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditTodoResponse)
	err := c.cc.Invoke(ctx, TodoDomain_EditTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoDomainServer is the server API for TodoDomain service.
// All implementations must embed UnimplementedTodoDomainServer
// for forward compatibility.
//
// TodoDomain service provides core business logic for managing todos
type TodoDomainServer interface {
	// CreateTodo creates a new todo item
	CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error)
	// CompleteTodo marks a todo as completed
	CompleteTodo(context.Context, *CompleteTodoRequest) (*CompleteTodoResponse, error)
	// ListTodos retrieves all todos for a user
	ListTodos(context.Context, *ListTodosRequest) (*ListTodosResponse, error)
	// DeleteTodo soft-deletes a todo
	DeleteTodo(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error)
	// EditTodo updates a todo's title or description
	EditTodo(context.Context, *EditTodoRequest) (*EditTodoResponse, error)
	mustEmbedUnimplementedTodoDomainServer()
}

// UnimplementedTodoDomainServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTodoDomainServer struct{}

func (UnimplementedTodoDomainServer) CreateTodo(context.Context, *CreateTodoRequest) (*CreateTodoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedTodoDomainServer) CompleteTodo(context.Context, *CompleteTodoRequest) (*CompleteTodoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTodo not implemented")
}
func (UnimplementedTodoDomainServer) ListTodos(context.Context, *ListTodosRequest) (*ListTodosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTodos not implemented")
}
func (UnimplementedTodoDomainServer) DeleteTodo(context.Context, *DeleteTodoRequest) (*DeleteTodoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTodo not implemented")
}
func (UnimplementedTodoDomainServer) EditTodo(context.Context, *EditTodoRequest) (*EditTodoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditTodo not implemented")
}
func (UnimplementedTodoDomainServer) mustEmbedUnimplementedTodoDomainServer() {}
func (UnimplementedTodoDomainServer) testEmbeddedByValue()                    {}

// UnsafeTodoDomainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoDomainServer will
// result in compilation errors.
type UnsafeTodoDomainServer interface {
	mustEmbedUnimplementedTodoDomainServer()
}

func RegisterTodoDomainServer(s grpc.ServiceRegistrar, srv TodoDomainServer) {
	// If the following call panics, it indicates UnimplementedTodoDomainServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TodoDomain_ServiceDesc, srv)
}

func _TodoDomain_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDomainServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoDomain_CreateTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDomainServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoDomain_CompleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDomainServer).CompleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoDomain_CompleteTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDomainServer).CompleteTodo(ctx, req.(*CompleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoDomain_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDomainServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoDomain_ListTodos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDomainServer).ListTodos(ctx, req.(*ListTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoDomain_DeleteTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDomainServer).DeleteTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoDomain_DeleteTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDomainServer).DeleteTodo(ctx, req.(*DeleteTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoDomain_EditTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoDomainServer).EditTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TodoDomain_EditTodo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoDomainServer).EditTodo(ctx, req.(*EditTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TodoDomain_ServiceDesc is the grpc.ServiceDesc for TodoDomain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoDomain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "todo.v1.TodoDomain",
	HandlerType: (*TodoDomainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoDomain_CreateTodo_Handler,
		},
		{
			MethodName: "CompleteTodo",
			Handler:    _TodoDomain_CompleteTodo_Handler,
		},
		{
			MethodName: "ListTodos",
			Handler:    _TodoDomain_ListTodos_Handler,
		},
		{
			MethodName: "DeleteTodo",
			Handler:    _TodoDomain_DeleteTodo_Handler,
		},
		{
			MethodName: "EditTodo",
			Handler:    _TodoDomain_EditTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
